coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: no
    patch: yes
    changes: no
    paths:
      - "smarca5"

comment:
  layout: "header, diff, changes, tree"
  behavior: default
