name: Lint

on: [push]

jobs:
  lint:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
       os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      
      - name: Install Poetry
        run: python -m pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Lint with flake8
        run: poetry run flake8 smarca5/ tests/

      - name: Lint docstrings with pydocstyle
        run: poetry run pydocstyle smarca5/ tests/

      - name: Type check the main code
        run: poetry run mypy --disallow-untyped-defs smarca5/

      - name: Type check the tests
        run: poetry run mypy --check-untyped-defs tests/
